"""Pydantic models for BOT-FORGE spec validation and pipeline state."""

from __future__ import annotations

import re
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


class Platform(str, Enum):
    TELEGRAM = "telegram"
    DISCORD = "discord"
    SLACK = "slack"
    CLI = "cli"
    WEB_API = "web-api"
    CUSTOM = "custom"


class LogLevel(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class PipelineStage(str, Enum):
    INTAKE = "intake"
    PLAN = "plan"
    RETRIEVE_DOCS = "retrieve_docs"
    GENERATE = "generate"
    TEST = "test"
    REVIEW = "review"
    PACKAGE = "package"
    DEPLOY = "deploy"
    DONE = "done"
    FAILED = "failed"


class EnvVarSpec(BaseModel):
    name: str
    description: str
    required: bool = True
    default: Optional[str] = None


class BotSpec(BaseModel):
    """Specification for a bot to be generated by BOT-FORGE."""

    name: str = Field(..., min_length=2, max_length=50)
    platform: Platform
    description: str = Field(..., min_length=3, max_length=500)
    language: str = "python"
    features: list[str] = Field(default_factory=lambda: ["echo"])
    env_vars: list[EnvVarSpec] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    include_docker: bool = True
    include_ci: bool = True
    include_tests: bool = True
    logging_level: LogLevel = LogLevel.INFO

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        slug = re.sub(r"[^a-z0-9-]", "-", v.lower()).strip("-")
        slug = re.sub(r"-+", "-", slug)
        if not slug:
            raise ValueError("name must produce a valid slug")
        return slug


class ProjectPlan(BaseModel):
    """Generated project plan from a validated spec."""

    spec: BotSpec
    files_to_generate: list[str] = Field(default_factory=list)
    platform_deps: list[str] = Field(default_factory=list)
    context_notes: list[str] = Field(default_factory=list)


class TestResult(BaseModel):
    passed: bool
    total: int = 0
    failures: int = 0
    output: str = ""


class ReviewReport(BaseModel):
    passed: bool
    issues: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class JobRecord(BaseModel):
    """Tracks a bot-generation job through the pipeline."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    spec: BotSpec
    stage: PipelineStage = PipelineStage.INTAKE
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    output_path: Optional[str] = None
    test_result: Optional[TestResult] = None
    review_report: Optional[ReviewReport] = None
    error: Optional[str] = None

    def advance(self, stage: PipelineStage) -> None:
        self.stage = stage
        self.updated_at = datetime.now(timezone.utc).isoformat()

    def fail(self, error: str) -> None:
        self.error = error
        self.stage = PipelineStage.FAILED
        self.updated_at = datetime.now(timezone.utc).isoformat()
